name: 获取股票价格

on:
  schedule:
    - cron: "*/5 9-14 * * 1-5"  # 每周一到周五的9点到14点，每5分钟运行一次

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests BeautifulSoup4

      - name: 检出代码
        uses: actions/checkout@v2

      - name: 运行 Python 脚本
        run: python test1.py
